theme: jekyll-theme-cayman

# Name of your blog (this will show up at the top of your page and in the RSS feed)
name: The Quest of My Research -- thn's blog name

title: The Quest of My Research -- thn's blog title

# Short description (goes below the title; it will also be used in the RSS feed)
#description: This is a sample Jekyll Blog.

# Your name, as you want it to appear underneath each post and in the footer
author: Tran Hung Nghiep

# Your email if you want it to be linked on the contact page
author_email: nghiepth@nii.ac.jp

# Exclude metadata and development time dependencies (like Grunt plugins)
exclude: [README.markdown, package.json, grunt.js, Gruntfile.js, Gruntfile.coffee, node_modules]
