# Site settings
title:            The Quest of My Research
description:      <br>
url:              http://scienceinsights.online
baseurl:          http://scienceinsights.online

author:
  name:           Hung-Nghiep Tran
  email:          tranhungnghiep at g mail
  url:            http://tranhungnghiep.github.io

# Custom vars
tagline:          Science Insights Online
sidebar_title:    The Quest <br> of <br> My Research


# Build settings
markdown: kramdown
permalink: pretty
paginate: 5
paginate_root: "/recent_posts/"
paginate_path: "/recent_posts/page:num"

# Gems plugins
plugins: [jekyll-paginate, jekyll-gist]
