title: The Quest of My Research

# Short description (goes below the title; it will also be used in the RSS feed)
#description: This is a sample Jekyll Blog.

# For RSS
name: The Quest of My Research

# Your name, as you want it to appear underneath each post and in the footer
author: Tran Hung Nghiep

# Your email if you want it to be linked on the contact page
author_email: nghiepth@nii.ac.jp

disqus: thnbiz

theme: jekyll-theme-cayman

markdown: kramdown
